// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    ItemAdder: typeof import('./src/components/ItemAdder.vue')['default']
    KanbanPanel: typeof import('./src/components/KanbanPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoryAdder: typeof import('./src/components/StoryAdder.vue')['default']
    StoryPanel: typeof import('./src/components/StoryPanel.vue')['default']
    StoryTab: typeof import('./src/components/StoryTab.vue')['default']
    TaskAdder: typeof import('./src/components/TaskAdder.vue')['default']
  }
}
